### ISSUE TITLE
Hayward Eyespool wifi module on pool heat pump

### ISSUE THREAD

**Issue by Cook23** [cryptk/haomnilogic-local#107]
Hello, 

Seems not working with Hayward EyesPool module. Didn't connect at all. 

Didn't found much information about this module and Home Assistant. 

If someone have some information about it thanks in advance.

**Comment by lordcoxis** [comment]
I also have a Hayward pool heat pump with the Eyespool module, it seems that this is not supported in Home Assistant yet.

**Comment by cryptk** [comment]
I have no idea what a Hayward EyesPool is... can you give me some information about it?

**Comment by lordcoxis** [comment]
In my case it's a pool heatpump that uses a Hayward [Wi-Fi module](https://www.hayward.fr/photoforum/Smartemp_Fr_GB.pdf). the Android application is called [EyesPool Inverter Connect](https://play.google.com/store/apps/details?id=com.hayward.hayward4&hl=en). I'm more than happy to try and do some tests or debugging if necessary.

**Comment by cryptk** [comment]
Is it controlled by the OmniLogic? It sounds like it has it's own app, which would mean control of that device is outside of the scope of this integration.

**Comment by lordcoxis** [comment]
Yeah it has it's own mobile phone app, not Omnilogic..

**Comment by cryptk** [comment]
That would require it's own integration then. This integration is scoped to the OmniLogic only.
