### ISSUE TITLE
Small bug in Heater status

### ISSUE THREAD

**Issue by mikesalz** [cryptk/haomnilogic-local#113]
I just noticed that the heater shows Off (uppercase O) or on (lowercase O).  I think both should be upper, right?

![image](https://github.com/user-attachments/assets/9c286628-1f6e-4b4f-8700-2c9d80f32a97)

**Comment by cryptk** [comment]
I believe that is an issue with the Home Assistant frontend.  The relevant lines of code in this integration are here https://github.com/cryptk/haomnilogic-local/blob/main/custom_components/omnilogic_local/water_heater.py#L104 and I am using the STATE_ON and STATE_OFF const values (as an integration should).  It's up to the frontend how it wants to render it though.
