### ISSUE TITLE
add support for setting the light color via rgb?

### ISSUE THREAD

**Issue by wez** [cryptk/haomnilogic-local#36]
I expose certain devices to HomeKit for ease of use by the rest of my family.

It would be fantastic if this integration could support parsing an rgb color request into the closest matching pre-defined static color effect so that setting the color of the lights is more natural and easy.

**Comment by cryptk** [comment]
The issue with that is I don't know what the RGB values of the existing colors are, all I have from the Omni API are names of colors and shows.  I also wouldn't know where to begin with writing a "best fit" style algorithm to map the colors around like that.

Unfortunately, I think we are going to have to stick with a list of effects

**Comment by wez** [comment]
Would you be opposed to a PR that takes a stab at implementing this?

**Comment by cryptk** [comment]
Have at it! PR's are very welcome!

**Comment by cryptk** [comment]
I do have one reservation about the functionality.  I'm concerned that it might lead people to believe that the integration provides functionality beyond what it actually does.  If someone sends an RGB value and they get something different than what they request, that may lead them to believe that there is something wrong with the integration.  I am a bit worried about getting tickets such as "I set the light to light purple, but I got deep purple instead".

**Comment by wez** [comment]
Understandable; I think that provided that the reported color value quickly snaps to the approximated value it will feel reasonably clear to folks while they are selecting colors in the color wheel or whatever UI they are using. I've used a couple of devices with similar behavior, and it wasn't especially jarring.

**Comment by cryptk** [comment]
Sounds good, let me know if you get something working and I'll be happy to test it out!

**Comment by irlkitcom** [comment]
This would be great, I use HomeKit Bridge and the effects can't be passed to HomeKit but I believe I could get an RGB switch going!

**Comment by cryptk** [comment]
@irlkitcom one thing to know, this would not allow you to show any color on the light... If it were implemented (which I have no plans to implement it myself) then all it would be able to do is select a "closest match" color from the ones already available to whatever RGB you asked for.

**Comment by cryptk** [comment]
The more I think about this, I don't think there is a reasonably way to implement a "Tell the light RGB, but have it auto-select a preset color from the very limited set that kinda matches" without it creating a lot of confusion and issue reports.  

Additionally, I want to keep the underlying library, and the integration, to functionality that is actually supported by the controller.  If people need a "best match" algorithm of sorts, they should implement that outside of the integration and then have that request the integration to perform an action that the lights are actually capable of.

I'm going to close this as WONTFIX.
