### ISSUE TITLE
error upgrading to 0.2.0

### ISSUE THREAD

**Issue by wez** [cryptk/haomnilogic-local#43]
I see this in the logs:

```
2023-06-07 06:59:21.944 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Omnilogic' for omnilogic_local integration not ready yet: Failed to parse MSP Configuration: 1 validation error for MSPConfig
Backyard -> Body-of-water -> 0 -> Pump
value is not a valid list (type=type_error.list); Retrying in background
```

the various entities are all unavailable.  Switching back to 0.1.0 brings them back.

Is there some additional info I can provide that will help resolve this?

**Comment by cryptk** [comment]
Should be an easy fix, working on an update now, just taking a while because of the current GitHub incident affecting PRs and checks

**Comment by cryptk** [comment]
I have the fix ready in the underlying library, just can't get the library built or published to pypi because of https://www.githubstatus.com/incidents/1g1gkh0qpyvs

**Comment by cryptk** [comment]
@wez release 0.2.1 should have this fixed

**Comment by wez** [comment]
Confirmed, thanks!
