### ISSUE TITLE
Spillover Spa and Motorized Cover Lockout

### ISSUE THREAD

**Issue by madasus** [cryptk/haomnilogic-local#63]
Hello,

First off - thank you for this interface!

I have a couple of items that aren't showing up for my pool.

1. I have a spillover spa which is controlled through OmniLogic.  I don't see that option in this interface.
2. I have an auto cover which has a lock out relay which prevents the spa spillover when the cover is closed.  Would there be a way to read this relay from OmniLogic?

Let me know what information I can provide to help get these into the system.

Regards

M

**Comment by cryptk** [comment]
Adding spillover support isn't in yet, but it's on the list for sure. As far as the cover interlock, there isn't a way to read that sensor directly in the examples that I've seen previously, but I did have someone else use the whyOn attribute on a valve actuator that was tied to their cover interlock to be able to determine that the cover interlock was active.

**Comment by madasus** [comment]
Thanks - i'm happy to test or provide whatever information you might need for the spillover stuff.

Can you elaborate a bit on the "whyOn" example - where do I find that?

**Comment by Paulbhyo** [comment]
Each valve has a why_on state which changes with schedules and other things,  but with an interlock that shuts off a valve,  the why_on state in my case was 10.   Check out the states of your valves or relays that get imported and verify its the same.  this was the cleanest way we found to "monitor" the EXT Input.   
![image](https://github.com/cryptk/haomnilogic-local/assets/109493887/780eff21-9dd6-4e26-b3c3-338258baabd0)
![image](https://github.com/cryptk/haomnilogic-local/assets/109493887/0ec91215-9ca6-438f-8dc4-e06ab4e964c2)

I have another messy way, that requires you to add an interlock to an unused relay... but its not required if your already interlocked with other equipment.

**Comment by madasus** [comment]
mine looks a bit different.  For me the interlock is only tied in to the spillover pump option.  Maybe thats why i don't see it yet?

![image](https://github.com/cryptk/haomnilogic-local/assets/9310056/7db4bff3-316f-479e-bcae-5879c0011f21)

**Comment by cryptk** [comment]
@madasus can you upload the diagnostic data from the integration? Then we can see if there is a bit of data we can expose

**Comment by Paulbhyo** [comment]
I wonder if that "unavailable" State is actually something else missing from the state list?

**Comment by madasus** [comment]
[config_entry-omnilogic_local-xxx.json.txt](https://github.com/cryptk/haomnilogic-local/files/11850804/config_entry-omnilogic_local-xxx.json.txt)

here it is

**Comment by cryptk** [comment]
the "unknown" is because your filter has a whyOn status of 18, which is undocumented, and it's failing to parse it into a textual representation... seems the docs I was provided are incomplete

**Comment by cryptk** [comment]
I'm not sure what these extra whyOn states for the filter mean, but for now I'm going to add them as "UNKNOWN", which will get the integration up and running, I can update the names of them in the future if we ever determine what they actually mean.

**Comment by madasus** [comment]
is that code anything i might be able to resolve through their web interface or other source?

**Comment by cryptk** [comment]
it's possible... I just pushed release 0.5.2 which adds some values to the filter whyOn enum, you should see it as "Unknown 18" now, and the switch should be available to use.  If you can test some things and see what causes it to go to a whyOn of "Unknown 18", that would be awesome.  Try opening and closing your cover, or maybe changing the spillover mode between pool/spa/spillover and see what combination of things makes it go to 18.

**Comment by cryptk** [comment]
I split the request for controlling spillover to #67

**Comment by madasus** [comment]
I just turned the spa on and off again and now that 18 is gone.

![image](https://github.com/cryptk/haomnilogic-local/assets/9310056/7e68d21a-0a4f-4300-88db-692edd4b00f7)

**Comment by Paulbhyo** [comment]
most likely the interlock is released when the spa filter pump is able to run.  ?? Do you have to open your auto cover to run the spa?

**Comment by madasus** [comment]
no - i can run the spa with the cover closed i'm just not able to run the spillover option on the pool pump with the cover closed.

**Comment by Paulbhyo** [comment]
I think the "why_on" can be from anything that is controlling the device,  manually with the toggle, schedule, interlock etc.  you just have to play with it and see if you find some correlation to the state and what is controlling it.     So do you have a Valve that controls the spill over then?  I would think the Why_on state of that could be indicating the Cover position.

**Comment by madasus** [comment]
i agree - i do have a valve for that but not yet visible in this integration.  Once thats added I can probably debug further.

I think you might be right on the 18 - I think that might be when the schedule turns off the valve.  I'll look in the morning when it goes through the next shutdown

**Comment by cryptk** [comment]
there is a `Timer On` option (it's 14), I wonder if 18 is `Timer Off`.

For what it's worth, you should be able to control things in the OmniLogic app to replicate scenarios and then observe the whyOn attribute in the integration next time the integration updates (default is every 10s)

**Comment by cryptk** [comment]
Do you by chance have a schedule set for your spillover? I wonder if 18 could mean that it tried to activate it for scheduled spillover, but it couldn't, because the pool cover interlock was active?

**Comment by madasus** [comment]
I have a schedule for the spa (no spillover) and then a schedule for the pool (full) and then a later schedule for the pool (half).  I think your TImer Off guess is a good one - i'll check tomorrow morning to see if it retuns after the timer expires.

**Comment by madasus** [comment]
Confirmed.  "Unknown 18" is when the spa pump is shut off as a result of the automated schedule

**Comment by cryptk** [comment]
I'll update it to say something like Timer Off for 18 then

**Comment by madasus** [comment]
tks - i'll keep an eye out for when the spillover spa valve shows up and we can try and figure out the interlock at that point.  I thought the interlock was presented as a unique relay in the data pull but maybe not?

**Comment by Paulbhyo** [comment]
The interlock input is not in any data sent from the controller to the cloud.  If you go onto haywards cloud website, you won't find it.  Therefore it's not a sensor that can be pulled from the data that is sent.  We can only see it on how it impacts other devices.   

If you have a spare relay,  you can set the interlock to force it on and off.  The relay would come in as a switch. I have tried that and the integration does pull the new switch In to the system..

**Comment by Paulbhyo** [comment]
That is in the configuration from the MSP.  But it's not in the regular data exchange (telemetry) that is received from a query.

**Comment by cryptk** [comment]
Going to go ahead and close this one, initial spillover support is released and unfortunately the omniologics don't return any telemetry for the current state of interlocks so I can't add that functionality to the integration
