### ISSUE TITLE
Feat: Add ORP and PH sensors

### ISSUE THREAD

**Issue by spraguej248** [cryptk/haomnilogic-local#73]
I have both the ORP and PH sensors and automatic dispensers.  I'm happy to help out with testing if the need arises.

Thanks for the great integration!

**Comment by cryptk** [comment]
Can you start by pulling the diagnostic data from the integration and attaching it to this issue? My kids go back to school in a couple of weeks and I should have time to work on some of these features once that happens.

**Comment by spraguej248** [comment]
Sure, I'm attaching it here.  Thanks!

[config_entry-omnilogic_local-e54490100346440d70659401fd412bc4.json.txt](https://github.com/cryptk/haomnilogic-local/files/12222194/config_entry-omnilogic_local-e54490100346440d70659401fd412bc4.json.txt)

**Comment by matthew-larner** [comment]
I really appreciate your work on this @cryptk and @spraguej248. I'm just about to buy an Omnilogic system so this feature would be amazing. I'm happy to beta test too if that helps.

**Comment by Tobypoodle** [comment]
Hi, I also have ORP and PH sensors so would love to see these added.   I use the HL-CHEM "Sense and Dispense" that the Omnilogic then controls little chem pumps for liquid chlorine and muratic acid. 

Great integration, good to see a local version as the Omnilogic servers can flake regularly and nice to be able to see/control things from the local network.  Let me know how I can help as I am somewhat technical.

**Comment by cryptk** [comment]
@matthew-larner @Tobypoodle @spraguej248 can you please install the version "main" inside HACS for the integration and see if you have pH sensors now? Once you verify that, I can get ORP in as well.

**Comment by matthew-larner** [comment]
Great thanks! It will be another month before my omnilogic system is installed, but I'll be happy to test then.

**Comment by spraguej248** [comment]
I do have the ph sensor coming through now, thank you!  A minor thing
though, the value that comes through does not include the ph offset.  For
ph, in the Omnilogic app, there is a field where you manually enter a
number to correct the value of the ph.  Is it possible to add a blank
offset field in the configuration, then show the sum of the actual ph value
from omnilogic plus the offset as the ph sensor value?

The home assistant omnilogic core integration does this as well.
Screenshot below.  The offset field exists in the configuration section.
The displayed ph sensor value is the sum of the actual omnilogic value plus
the ph offset.  This is only required for the ph.  There is no adjustment
for ORP.

[image: image.png]

Thank you!!!

**Comment by Tobypoodle** [comment]
Yep, can see PH now, great and thank you!   Ditto spraguej248 comments on PH offset.

**Comment by cryptk** [comment]
I have the data for the pH offset in the integration already, I just assumed that the pH value was already including that offset, evidently it isn't. I'm going to be busy for the next couple of days, but I'll get a version pushed out that offsets the value properly.

**Comment by cryptk** [comment]
@amattas feel free to send in pull requests! I didn't work on the project much over the winter because I wasn't using my pool, but now that we're back into pool season, I'm hoping to knock out some of the various feature requests and issues

**Comment by cryptk** [comment]
#104 should fix the calibration offset issue as well as add some extra data as attributes to the sensor (ORP, raw value, calibration offset, high/low alarm thresholds, etc).

Take a look at version 0.7.4 and let me know if I need to address this further!

**Comment by spraguej248** [comment]
Yes, the ph sensor pulls the adjusted number correctly now.  Nice you are
able to get the adjusted number and not have to worry about it in HA.
Thanks!  :)

Here's the other sensors/controls I see in 0.7.4.  I see that there is a
chlorinator switch which does turn my sense & dispense chlorinator on/off
(not sure if that was there previously?).  Here's some screen shots showing
what comes over from 0.7.4.

Thank you!

[image: image.png]
[image: image.png]

**Comment by amattas** [comment]
So I just updated to 0.7.5 and PH showed up, but I don't see ORP. And then I just read back through and realized it was under the PH sensor. 

I'd probably break it out from a usability standpoint. With it combined I can't use the default trend charts, etc that you get either.

**Comment by cryptk** [comment]
Unopened #106 to handle some more improvements for the Sense and dispense equipment, including splitting the orp out to its own sensor

**Comment by cryptk** [comment]
@spraguej248 on the off-chance that you see this.  I'm working on adding support for liquid dispensing CSAD units, and you are the only person who's diagnostic data I have that shows that you have one.  Is there any chance you could get me some packet captures of you setting your chlorinator to different values?

**Comment by spraguej248** [comment]
I'm happy to help however I can.  I don't know how to do packet captures,
but if you can tell me what to do I should be able to do it.  Sorry, I'm a
pretty good power user but not as skilled at programming anymore.

Thanks!
