### ISSUE TITLE
Unable to load lights after 2024.2.1 upgrade

### ISSUE THREAD

**Issue by mikesalz** [cryptk/haomnilogic-local#86]
I upgraded to HA 2024.2.1 today.  Since then, most of my Omnilogic entities still work.  But lights are failing.  Error below:

> 
> Logger: homeassistant.components.light
> Source: helpers/entity_platform.py:352
> Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
> First occurred: 9:37:23 PM (2 occurrences)
> Last logged: 9:40:02 PM
> 
> Error while setting up omnilogic_local platform for light
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
>     attr.update(self.state_attributes or {})
>                 ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1129, in state_attributes
>     self.__validate_color_mode(color_mode, legacy_supported_color_modes, effect)
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1093, in __validate_color_mode
>     effect_color_modes = supported_color_modes | {ColorMode.ONOFF}
>                          ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
> TypeError: unsupported operand type(s) for |: 'list' and 'set'

**Comment by mikesalz** [comment]
I just noticed that someone else posted a similar issue.  Sorry for duplicating!!

**Comment by mikesalz** [comment]
@cryptk  I bet this has something to do with the issue!

https://developers.home-assistant.io/blog/2024/01/23/light-color-mode-changes/

**Comment by mikesalz** [comment]
FYI - I rolled back to 2024.1.6 this morning and my OmniLogic lights are now working.  So the issue does seem to be related to the changes in the February HA release.

**Comment by cryptk** [comment]
@mikesalz should fixed with 0.7.1 of the integration

**Comment by mikesalz** [comment]
Thanks @cryptk!  I just installed it and so far everything looks perfect.  I really appreciate your help!
