### ISSUE TITLE
Second Variable Speed Pump Not Showing Power Under Sensors

### ISSUE THREAD

**Issue by toddhutch** [cryptk/haomnilogic-local#88]
I have two variable speed pumps, and I noticed that the second pump is not showing power.  All of the other controls are showing for the second pump.  I upgraded to .71 and the lights work great.  I unwinterized the second pump today.  I thought perhaps it was because I've had the breaker off on the second pump, as it was winterized. So I shutdown the system, and powered off the omnilogic controller thinking perhaps that we fix the issue.  I don't see any difference.  I've rebooted the HA Yellow device that I use.  In the iphone app both pumps have the Diagnostics and power showing.
I'll attached the HA diagnostics to this issue. I'm available to test and try things. 👍
[config_entry-omnilogic_local-629a5add5b1b3a9386d23e3a68efb06f (3).json](https://github.com/cryptk/haomnilogic-local/files/14324554/config_entry-omnilogic_local-629a5add5b1b3a9386d23e3a68efb06f.3.json)

**Comment by cryptk** [comment]
Hey @toddhutch I just took a look at your telemetry and unfortunately, I think that only Filter devices report power usage.  Here are the relevant bits of the telemetry from your debug file:

```
<?xml version="1.0" encoding="UTF-8" ?>
<STATUS version="1.11">
      ... SNIPPED ...
    <Filter systemId="12" filterState="1" filterSpeed="75" valvePosition="1" whyFilterIsOn="14" fpOverride="0" reportedFilterSpeed="75" power="631" lastSpeed="25" />
   ... SNIPPED ...
    <Pump systemId="15" pumpState="1" pumpSpeed="50" lastSpeed="50" whyOn="8" />
   ... SNIPPED ...
</STATUS>
```

You can see in there that your Filter has a power parameter, but the pump device unfortunately does not.  Not much I can do there.
