### ISSUE TITLE
Better selection of equipment icons

### ISSUE THREAD

**Issue by cryptk** [cryptk/haomnilogic-local#9]
Many pieces of equipment expose what type of equipment they control, for example, relays have a Function parameter which can be set to things such as RLY_WATER_FEATURE, RLY_FOUNTAIN, RLY_BLOWER, etc... we should use this data, if available, to select an appropriate icon for the relay

**Comment by MHillyer** [comment]
I like the heater status icon, but for the pool spa heater status it's a thermometer, not a flame.
Wonder if you could use mdi:fire when idle, and mdi:fire-alert when active.
I don't know that they are available, but 24 x 24

material-symbols:local-fire-department-outline and material-symbols:local-fire-department would be great.
