### ISSUE TITLE
Reloading using HACS to upgrade from 0.5.3 not updating version in integration

### ISSUE THREAD

**Issue by toddhutch** [cryptk/haomnilogic-local#95]
Maybe this is the correct place to put this, when I look a tthe OmniLogic in HA ->Settings->OmniLogic Local.  I see the attached image that shows 0.5.3, but when in HACS, it shows 0.7.2.
![image](https://github.com/cryptk/haomnilogic-local/assets/4127125/bc64d496-3616-41f9-b635-85fdf8e0558c)
![image](https://github.com/cryptk/haomnilogic-local/assets/4127125/337650e3-f3ee-4029-a860-50d80977406e)

**Comment by agodinij** [comment]
I see the same.

**Comment by cryptk** [comment]
that's mostly just a display issue.  It's because HACS goes by the git tag and Home Assistant goes by the version parameter in manifest.json.  The version listed in HACS is correct, I just need to remember to update the version value in manifest.json (or have CI do it for me)
